### ISSUE TITLE
Guess completion modal

### ISSUE THREAD

**Issue by CubePresser** [OSU-CS492-W19/final-project-team-15#9]
Modal that appears when a guess has been made. 

- [x] Appears on guess-button-clicked event
- [x] Indicates to the user whether or not they chose correctly or incorrectly
- [x] Displays score for that guess
- [x] X button to close modal
- [x] "Listen on spotify" button that calls an implicit intent to send the user to either a web browser or the spotify app to listen to the selected song

**Comment by Brallen** [comment]
Modal appears to tell user if they were correct or incorrect and gives the option to close or open song in spotify
